// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC42iIlqGBT8yOuTHHhAJbvxhpwxeLQqFQ',
    appId: '1:377806584339:web:ccae67ae90e52722561de6',
    messagingSenderId: '377806584339',
    projectId: 'mynotes-surajit',
    authDomain: 'mynotes-surajit.firebaseapp.com',
    storageBucket: 'mynotes-surajit.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmx6BPCKk5xi4m_YXl2wfybVEHziA4VHE',
    appId: '1:377806584339:android:a414ba83e8151769561de6',
    messagingSenderId: '377806584339',
    projectId: 'mynotes-surajit',
    storageBucket: 'mynotes-surajit.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZdMrgin1QAL2Ryx5wJLdNA0RYcC8NVT4',
    appId: '1:377806584339:ios:ab0e80ed2f7e9619561de6',
    messagingSenderId: '377806584339',
    projectId: 'mynotes-surajit',
    storageBucket: 'mynotes-surajit.appspot.com',
    iosBundleId: 'com.flutter.surajitshaw',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZdMrgin1QAL2Ryx5wJLdNA0RYcC8NVT4',
    appId: '1:377806584339:ios:ab0e80ed2f7e9619561de6',
    messagingSenderId: '377806584339',
    projectId: 'mynotes-surajit',
    storageBucket: 'mynotes-surajit.appspot.com',
    iosBundleId: 'com.flutter.surajitshaw',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC42iIlqGBT8yOuTHHhAJbvxhpwxeLQqFQ',
    appId: '1:377806584339:web:26d1562ff7e101db561de6',
    messagingSenderId: '377806584339',
    projectId: 'mynotes-surajit',
    authDomain: 'mynotes-surajit.firebaseapp.com',
    storageBucket: 'mynotes-surajit.appspot.com',
  );
}
